onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -group DUT /tb_asic_top/dut/CLK100MHZ
add wave -noupdate -group DUT /tb_asic_top/dut/BTN
add wave -noupdate -group DUT /tb_asic_top/dut/SW
add wave -noupdate -group DUT /tb_asic_top/dut/RLED
add wave -noupdate -group DUT /tb_asic_top/dut/GLED
add wave -noupdate -group DUT /tb_asic_top/dut/BLED
add wave -noupdate -group DUT /tb_asic_top/dut/LED
add wave -noupdate -group DUT /tb_asic_top/dut/UNCONNECTED72
add wave -noupdate -group DUT /tb_asic_top/dut/UNCONNECTED73
add wave -noupdate -group DUT /tb_asic_top/dut/UNCONNECTED74
add wave -noupdate -group DUT /tb_asic_top/dut/UNCONNECTED75
add wave -noupdate -group DUT /tb_asic_top/dut/UNCONNECTED76
add wave -noupdate -group DUT /tb_asic_top/dut/UNCONNECTED77
add wave -noupdate -group DUT /tb_asic_top/dut/UNCONNECTED78
add wave -noupdate -group DUT /tb_asic_top/dut/UNCONNECTED79
add wave -noupdate -group DUT /tb_asic_top/dut/UNCONNECTED80
add wave -noupdate -group DUT /tb_asic_top/dut/UNCONNECTED81
add wave -noupdate -group DUT /tb_asic_top/dut/UNCONNECTED82
add wave -noupdate -group DUT /tb_asic_top/dut/UNCONNECTED83
add wave -noupdate -group DUT /tb_asic_top/dut/UNCONNECTED84
add wave -noupdate -group DUT /tb_asic_top/dut/UNCONNECTED85
add wave -noupdate -group DUT /tb_asic_top/dut/UNCONNECTED86
add wave -noupdate -group DUT /tb_asic_top/dut/UNCONNECTED87
add wave -noupdate -group DUT /tb_asic_top/dut/UNCONNECTED88
add wave -noupdate -group DUT /tb_asic_top/dut/UNCONNECTED89
add wave -noupdate -group DUT /tb_asic_top/dut/UNCONNECTED90
add wave -noupdate -group DUT /tb_asic_top/dut/UNCONNECTED91
add wave -noupdate -group DUT /tb_asic_top/dut/UNCONNECTED92
add wave -noupdate -group DUT /tb_asic_top/dut/UNCONNECTED93
add wave -noupdate -group DUT /tb_asic_top/dut/UNCONNECTED94
add wave -noupdate -group DUT /tb_asic_top/dut/UNCONNECTED95
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/i_CLK100MHZ
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/BTN
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/SW
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/RLED
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/GLED
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/BLED
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/LED
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/out_reg_data_out
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/bus_data_out
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/addr_reg_data_out
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/alu_opcode
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/alu_data_out
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/ctrl_data_out
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/inst_reg_data_out
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/mac_data_out
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/mem_rdata
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/pc_counter
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/bus_sel_in
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/mac_opcode
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/data_reg_data_out
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED0
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED1
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED2
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED3
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED4
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED5
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED6
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED7
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED8
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED9
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED10
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED11
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED12
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED13
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED14
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED15
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED16
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED17
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED18
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED19
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED20
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED21
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED22
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED23
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED24
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED25
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED26
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED27
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED28
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED29
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED30
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED31
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED32
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED33
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED34
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED35
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED36
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED37
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED38
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED39
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED40
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED41
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED42
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED43
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED44
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED45
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED46
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED47
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED48
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED49
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED50
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED51
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED52
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED53
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED54
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED55
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED56
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED57
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED58
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED59
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED60
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED61
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED62
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED63
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED64
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED65
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED66
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED67
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED68
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED69
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED70
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/UNCONNECTED71
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/addr_reg_en
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/alu_acc_overflow
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/alu_acc_zero
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/data_reg_en
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/inst_reg_en
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/mem_wen
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/n_0
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/out_reg_en
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/pc_increment
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/pc_load
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/pc_out_of_range
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/pc_reset
add wave -noupdate -group mest_pro /tb_asic_top/dut/mest_pro/s_reset
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/clk
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/a_reset_n
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/start
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/alu_acc_overflow
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/alu_acc_zero
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/pc_out_of_range
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/inst_reg
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/pc_reset
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/pc_load
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/pc_increment
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/error_state
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/addr_reg_en
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/data_reg_en
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/mem_wen
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/inst_reg_en
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/out_reg_en
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/alu_opcode
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/mac_opcode
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/bus_sel_in
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/data_out
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/rom_addr
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/stateReg
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/bus_shift_reg
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/rom_shift_reg
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_0
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_1
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_2
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_3
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_4
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_5
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_6
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_7
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_8
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_9
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_10
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_11
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_12
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_13
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_14
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_15
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_16
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_17
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_18
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_19
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_20
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_21
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_22
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_23
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_24
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_25
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_26
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_27
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_28
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_29
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_30
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_31
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_32
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_33
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_34
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_35
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_36
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_37
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_38
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_39
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_40
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_41
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_42
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_43
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_44
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_45
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_46
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_47
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_48
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_49
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_50
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_51
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_52
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_53
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_54
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_55
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_56
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_57
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_58
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_59
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_60
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_61
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_62
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_63
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_64
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_65
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_66
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_67
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_68
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_69
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_70
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_71
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_72
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_73
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_74
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_75
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_76
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_77
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_78
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_79
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_80
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_81
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_82
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_83
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_84
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_85
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_86
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_87
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_88
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_89
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_90
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_91
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_92
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_93
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_94
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_95
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_96
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_97
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_98
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_99
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_100
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_101
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_102
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_103
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_104
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_105
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_106
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_107
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_108
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_109
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_110
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_111
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_112
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_113
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_114
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_115
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_116
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_117
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_118
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_119
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_120
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_121
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_122
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_123
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_124
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_125
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_126
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_127
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_128
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_129
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_130
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_131
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_132
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_133
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_134
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_135
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_136
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_137
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_138
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_139
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_140
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_141
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_142
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_143
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_144
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_145
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_146
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_147
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_148
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_149
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_150
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_151
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_152
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_153
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_154
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_156
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_158
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_159
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_160
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_161
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_162
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_163
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_164
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_165
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_166
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_167
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_168
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_169
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_170
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_171
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_172
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_173
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_174
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_175
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_176
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_177
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_178
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_179
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_180
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_198
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_199
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_209
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_210
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_211
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_212
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_213
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_214
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_215
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_216
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_217
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_221
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/n_241
add wave -noupdate -group cpu_controller /tb_asic_top/dut/mest_pro/cpu_controller/startReg
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {964 ps}
